# Generated by Django 4.0.4 on 2022-08-26 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placename', models.CharField(max_length=30)),
                ('hotelname', models.CharField(max_length=50)),
                ('cost', models.FloatField()),
                ('photo', models.ImageField(upload_to='images/')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hotels.country')),
            ],
        ),
    ]
