# Generated by Django 4.0.4 on 2022-08-29 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hotels.category'),
        ),
    ]
