# Generated by Django 4.0.4 on 2022-09-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_hotels_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='hotelname',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='placename',
            field=models.CharField(max_length=70),
        ),
    ]
